name: CI/CD - Main Branch

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '20'
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: npm install
    - name: Build project
      run: npm run build  # Assuming there's a build script defined
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: built-code
        path: 'path/to/your/built/code'  # Replace with the actual path

# No SSH deployment steps as requested


  deploy:  # New job for deployment

    runs-on: ubuntu-latest  # Can be configured to run on a different runner if needed

    needs: build  # This job depends on the successful completion of the "build" job
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: built-code
    - name: Deploy to server (Manual steps)
      # Since SSH access is unavailable, provide instructions on how to deploy the downloaded artifacts
      run: |
        echo "** Deployment Steps **"
        echo "1. Download the build artifact (built-code.zip) from the Actions tab."
        echo "2. Manually transfer the downloaded artifact to your server."
        echo "3. Extract the contents of the artifact on the server."
        echo "4. (Optional) Perform any additional deployment steps specific to your server environment."
        echo "** Note: These are manual steps as SSH access is not configured. **"

